# Generated by Django 4.1.13 on 2025-10-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
    ]
